dashboard/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^accept-invite$', views.accept_invite, name='accept-invite'),
    url(r'^decline-invite$', views.decline_invite, name='decline-invite'),
    url(r'^edit-profile$', views.edit_profile, name='edit-profile')
]

ubhacking/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from marketing.urls import urlpatterns as marketing_routes
from django.conf import settings

urlpatterns = [
    url(r'^dashboard/', include('dashboard.urls', namespace='dashboard')),
    url(r'^jet/', include('jet.urls', 'jet')),
    url(r'^admin/', admin.site.urls),
] + marketing_routes

if settings.DEBUG:
    from django.conf.urls.static import static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/models.py
from django.db import models
from django.contrib.auth.models import User
from lib.choices import SCHOOL_NAME_CHOICES, CLASS_STANDING_CHOICES, \
                        SHIRT_SIZE_CHOICES, STATUS_CHOICES
from django.db.models.signals import post_save
from django.dispatch import receiver


def resume_loc(instance, filename):
    return '/'.join(['profiles', str(instance.user.pk), filename])

class Profile(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE)

    dietary_restrictions = models.CharField(default="", max_length=128, blank=True)

    shirt_size = models.IntegerField(default=2, choices=SHIRT_SIZE_CHOICES)

    school = models.IntegerField(default=-1, choices=SCHOOL_NAME_CHOICES)

    major = models.CharField(default="Unknown", max_length=128)

    grade = models.IntegerField(default=0, choices=CLASS_STANDING_CHOICES)

    status = models.IntegerField(default=0, choices=STATUS_CHOICES)

    travel = models.BooleanField(default=False)

    resume = models.FileField(blank=True, null=True, upload_to=resume_loc)

    class Meta:
        db_table = "profile_tbl"

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

dashboard/forms.py
from django import forms
from lib.choices import CLASS_STANDING_CHOICES, SCHOOL_NAME_CHOICES, SHIRT_SIZE_CHOICES


class EditProfileForm(forms.Form):

    email = forms.EmailField(required=True)

    password = forms.CharField(required=False, widget=forms.PasswordInput, min_length=8)

    retype_password = forms.CharField(required=False, widget=forms.PasswordInput)

    first_name = forms.CharField(required=True, max_length=64)

    last_name = forms.CharField(required=True, max_length=64)

    school_major = forms.CharField(required=True, max_length=64)

    class_standing = forms.ChoiceField(required=True, choices=CLASS_STANDING_CHOICES)

    school_name = forms.ChoiceField(required=True, choices=SCHOOL_NAME_CHOICES)

    resume = forms.FileField(required=False)

    dietary_restrictions = forms.CharField(widget=forms.Textarea(attrs={'rows': 5}))

    shirt_size = forms.ChoiceField(required=True, choices=SHIRT_SIZE_CHOICES)

    travel_reimbursement = forms.BooleanField()

    def clean(self):
        password1 = self.cleaned_data.get('password')
        password2 = self.cleaned_data.get('retype_password')

        if password1 and len(password1) > 0 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")

        return self.cleaned_data

dashboard/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from . import forms
from lib.helpers import notify_form_errors
from lib.templatetags.ubhacking import can_change_acception
from lib.choices import STATUS_CHOICES, get_choice
from .models import Profile

def index(request):
    is_hacker = request.user.groups.filter(name='Hackers').exists()
    is_organizer = request.user.groups.filter(name='Organizers').exists()
    has_space = Profile.objects.filter(status=get_choice("Accepted", STATUS_CHOICES)).count() < 500

    return render(request, "dashboard/index.html", {'is_hacker': is_hacker,
                                                    'is_organizer': is_organizer,
                                                    'has_space': has_space})


def decline_invite(request):

    if not can_change_acception(request.user.profile.get_status_display()):
        messages.error(request, "This is an invalid operation!")
        return redirect('dashboard:index')

    request.user.profile.status = get_choice("Declined", STATUS_CHOICES)
    request.user.profile.save()

    messages.success(request, "Sorry to hear you can't make it :(")

    return redirect('dashboard:index')


def accept_invite(request):

    if not can_change_acception(request.user.profile.get_status_display()):
        messages.error(request, "This is an invalid operation!")
        return redirect('dashboard:index')

    request.user.profile.status = get_choice("Accepted", STATUS_CHOICES)
    request.user.profile.save()

    messages.success(request, "We'll see you there!")

    return redirect('dashboard:index')


def edit_profile(request):
    if request.method == 'POST':

        form = forms.EditProfileForm(request.POST, request.FILES)

        if form.is_valid():

            user = request.user

            # Update the user model
            user.email = form.cleaned_data["email"]
            user.username = form.cleaned_data["email"]

            user.first_name = form.cleaned_data["first_name"]
            user.last_name = form.cleaned_data["last_name"]

            if len(form.cleaned_data["password"]) > 0:
                user.set_password(form.cleaned_data["password"])
                messages.success(request, "Successfully updated password!")

            # Update the profile
            profile = user.profile
            profile.dietary_restrictions = form.cleaned_data["dietary_restrictions"]
            profile.shirt_size = form.cleaned_data["shirt_size"]
            profile.school = form.cleaned_data["school_name"]
            profile.major = form.cleaned_data["school_major"]
            profile.grade = form.cleaned_data["class_standing"]
            profile.travel = form.cleaned_data["travel_reimbursement"]

            if form.cleaned_data["resume"]:
                profile.resume = form.cleaned_data["resume"]

            user.save()
            profile.save()
            messages.success(request, "Successfully updated your profile!")

        else:
            notify_form_errors(request, form)

    else:
        form = forms.EditProfileForm()

    return render(request, "dashboard/edit-profile.html", {"form": form})

dashboard/templates/dashboard/_navbar.html
<nav data-sticky-container>
  <div data-sticky data-options="marginTop:0;" style="width:100%" data-sticky-on="small">
    <div class="title-bar" data-responsive-toggle="responsive-menu">
      <button class="menu-icon" data-toggle="responsive-menu"></button>
      <div class="title-bar-title" data-toggle="responsive-menu">UB Hacking 2017</div>
    </div>

    <div class="top-bar-container">
      <div class="top-bar" id="responsive-menu">
        <div class="top-bar-left hide-for-small-only">
          <ul class="menu">
            <li class="menu-text">
              <a href="{% url 'index' %}">UB Hacking 2017</a>
            </li>
          </ul>
        </div>
        <div class="top-bar-right">
          <ul class="menu vertical medium-horizontal">
            <li><a href="{% url 'dashboard:index' %}">Dashboard</a></li>
            <li><a href="{% url 'logout' %}">Log Out</a></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</nav>

dashboard/templates/dashboard/edit-profile.html
{% extends "base/base.html" %}
{% load static from staticfiles %}

{% load widget_tweaks %}
{% load ubhacking %}

{%block extra_css %}
  <link rel="stylesheet" href="{% static 'css/select2.css' %}"/>
{% endblock %}

{% block main %}
  <main class="grid-container grid-container-padded">
    <h2>Edit Your Profile</h2>

    <div class="grid-x grid-padding-x">
      <form class="cell" method="post" enctype="multipart/form-data" data-abide novalidate>
        {% csrf_token %}

        <fieldset class="fieldset">
          <legend>Account Information</legend>

          <div class="grid-x grid-margin-x">
            <label class="cell">Email Address
              {% render_field form.email type='email' placeholder='Email Address' value=request.user.email %}
            </label>

            <label class="cell medium-6">
              New Password
              {% render_field form.password placeholder='Password' %}
            </label>
            <label class="cell medium-6">Re-type New Password
              {% render_field form.retype_password placeholder='Retype Password' %}
            </label>
          </div>
        </fieldset>

        <fieldset class="fieldset">
          <legend>Basic Information</legend>

          <div class="grid-x grid-margin-x">
            <label class="cell medium-6">First Name
              {% render_field form.first_name placeholder='First Name' value=request.user.first_name %}
            </label>
            <label class="cell medium-6">First Name
              {% render_field form.last_name placeholder='Last Name' value=request.user.last_name %}
            </label>
            <label class='large-4 cell'>School Name
              <select class="select2" name="school_name" id="id_school_name">
                {% for choice in form.school_name.field.choices %}
                  <option {% if request.user.profile.school == choice.0%}selected{% endif %} value='{{choice.0}}'>{{choice.1}}</option>
                {% endfor %}
              </select>
            </label>
            <label class='medium-6 large-4 cell'>School Major
              {% render_field form.school_major placeholder='School Major' value=request.user.profile.major %}
            </label>

            <label class='medium-6 large-4 cell'>School Grade
              <select name='class_standing' id="id_class_standing">
                {% for choice in form.class_standing.field.choices %}
                  <option {% if request.user.profile.grade == choice.0%}selected{% endif %} value='{{choice.0}}'>{{choice.1}}</option>
                {% endfor %}
              </select>

            </label>
          </div>
        </fieldset>

        <fieldset class="fieldset">
          <legend>Logistics</legend>

          <div class="grid-x grid-margin-x">
            <label class='cell medium-6'>Dietary Restrictions
              <textarea name="dietary_restrictions" cols="40" rows="5" value="None" placeholder="Dietary Restrictions" required="" id="id_dietary_restrictions">{{request.user.profile.dietary_restrictions}}</textarea>
            </label>
            <label class='cell medium-6'>T-Shirt Size
              <select name='shirt_size' id="id_shirt_size">
                {% for choice in form.shirt_size.field.choices %}
                  <option {% if request.user.profile.shirt_size == choice.0%}selected{% endif %} value='{{choice.0}}'>{{choice.1}}</option>
                {% endfor %}
              </select>
            </label>
          </div>
        </fieldset>

        <fieldset class="fieldset">
          <legend>Other</legend>
            <label class="button hollow" for="resume">Upload Résumé</label>
            {% render_field form.resume class='show-for-sr' id='resume' accept='.pdf, application/pdf' %}
            {% if request.user.profile.resume %}
              <label>Current Resume: <a href="{{ request.user.profile.resume.url }}">{{ request.user.profile.resume|filename }}</a></label>
            {% endif %}
            <br/>

            <label style='margin-bottom: 0'>
              <input type="checkbox" name="travel_reimbursement" {% if request.user.profile.travel %}checked{%endif%} id="id_travel_reimbursement">
              (Non-UB students only) I would like to be considered for travel reimbursement.
            </label>
        </fieldset>

        <button class="button expanded">Update</button>
      </form>
    </div>
  </main>
{% endblock %}

{% block extra_javascript %}
  <script src='https://code.jquery.com/jquery-3.2.1.min.js'></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/js/select2.min.js"></script>
  <script src="{% static 'js/resume_upload.js' %}"></script>
  <script>
    $(function() {
    	$('.select2').select2({
        placeholder: 'School Name',
        width: 'element'
      });
    });
  </script>
{% endblock %}

dashboard/templates/dashboard/index.html
{% extends "base/base.html" %}
{% load ubhacking %}

{% block main %}
  <main class="grid-container grid-container-padded">
    <h2>Dashboard</h2>

    <div class="grid-x grid-padding-x grid-margin-x" style="margin-left: 5px; margin-right: 5px;">
      <p class="lead cell">Hello {{ request.user.first_name }}!</p>

      {% if is_hacker %}
        <div class="large-6 small-12">
          <p class="lead cell">Your Account</p>
          <p class="cell text-center" style="color: #11aac5; font-style: italic;">
            Acceptance status: {{ request.user.profile.get_status_display }}
          </p>
          {% if request.user.profile.get_status_display|can_change_acception %}
            <p class="cell">
              <span class="button-group align-center">
                <a href="{% url 'dashboard:decline-invite' %}" class="hollow button">Decline</a>
                {% if has_space %}
                  <a href="{% url 'dashboard:accept-invite' %}" class="button">Accept</a>
                {% endif %}
              </span>
            </p>
          {% endif %}
          <p class="cell">
            <span class="button-group align-center">
              <a href="{% url 'dashboard:edit-profile' %}" class="hollow button">Edit your profile</a>
            </span>
          </p>
        </div>

        <div class="large-6 small-12">
          <p class="lead cell">My Team</p>
        </div>

      {% endif %}

      {% if is_organizer %}
        <div class="fieldset large-12 medium-12">
          <p class="lead cell">Organizer Portal</p>
        </div>
      {% endif %}

      {% comment %}
        <div class="cell">
          <hr>
          <p>Organizer links (more coming soon):</p>
          <ul>
            <li><a href="{{ url_for('users.list_users') }}">List users</a></li>
            <li><a href="{{ url_for('users.list_invitations') }}">List pending invitations</a></li>
          </ul>
        </div>
      {% endif %}{% endcomment %}

      {# TODO: show application status for hackers #}

      {# TODO: show links to things the user's roles allow access to #}
    </div>
  </main>
{% endblock %}